"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import MainLayout from "@/components/layouts/MainLayout";
import { usePathname } from "next/navigation";
import Navbar from "@/components/layouts/Navbar";
import AuthGuard from "./AuthGaurd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const noNavbarPaths = ["/signup", "/signin"];
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}
      >
        <AuthGuard>
          {noNavbarPaths.includes(pathname) ? (
            <div className="h-screen flex justify-center items-center">
              {children}
              <Toaster />
            </div>
          ) : (
            <>
              {" "}
              <Navbar />
              <MainLayout>{children}</MainLayout>
              <Toaster />
            </>
          )}
        </AuthGuard>
      </body>
    </html>
  );
}
